tests/tiktok/test_tiktok.py::TiktokAudit::test_like_random
--------------------------------------------------------------------
Last Page: data:,
 Duration: 0.39s
  Browser: Chrome 121.0.6167.160
   Driver: chromedriver 121.0.6167.85
Timestamp: 1707427594  (Unix Timestamp)
     Date: Thursday, February 8, 2024
     Time: 4:26:34 PM  (EDT, UTC-04:00)
--------------------------------------------------------------------
Traceback:
  File "/Users/ihoonsun/Desktop/cs 315/project1/tiktok-like-experiment/tests/tiktok/test_tiktok.py", line 11, in test_like_random
    self.fetch_tiktok()
  File "/Users/ihoonsun/Desktop/cs 315/project1/tiktok-like-experiment/page_objects/PageTiktok.py", line 110, in fetch_tiktok
    self.chromebrowser.uc_open_with_reconnect('https://www.tiktok.com/en/',reconnect_time=5) #link to login page
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihoonsun/.virtualenvs/venv/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3691, in <lambda>
    lambda *args, **kwargs: uc_open_with_reconnect(
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihoonsun/.virtualenvs/venv/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 426, in uc_open_with_reconnect
    driver.execute_script('window.open("%s","_blank");' % url)
  File "/Users/ihoonsun/.virtualenvs/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihoonsun/.virtualenvs/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/Users/ihoonsun/.virtualenvs/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
Exception: Message: invalid session id
Stacktrace:
0   uc_driver                           0x0000000103012168 uc_driver + 4673896
1   uc_driver                           0x00000001030099c3 uc_driver + 4639171
2   uc_driver                           0x0000000102bfddeb uc_driver + 396779
3   uc_driver                           0x0000000102c3bb17 uc_driver + 650007
4   uc_driver                           0x0000000102c6c7a4 uc_driver + 849828
5   uc_driver                           0x0000000102c672b2 uc_driver + 828082
6   uc_driver                           0x0000000102c66b2d uc_driver + 826157
7   uc_driver                           0x0000000102bca6df uc_driver + 186079
8   uc_driver                           0x0000000102fd2380 uc_driver + 4412288
9   uc_driver                           0x0000000102fd7798 uc_driver + 4433816
10  uc_driver                           0x0000000102fb6d71 uc_driver + 4300145
11  uc_driver                           0x0000000102fd84e6 uc_driver + 4437222
12  uc_driver                           0x0000000102fa8d3c uc_driver + 4242748
13  uc_driver                           0x0000000102bc8f95 uc_driver + 180117
14  dyld                                0x0000000203ce2386 start + 1942
